# Generated by Django 3.2.14 on 2022-07-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_filter',
        ),
    ]
